### ISSUE TITLE
Error - This doesn't appear to be a valid credential file.

### ISSUE THREAD

**Issue by mlisle** [blockchain-certificates/wallet-android#47]
We have a user on Android 10.0 who receives an error when trying to import a credential into her wallet. 

![image](https://user-images.githubusercontent.com/14081049/72632999-88357780-3925-11ea-9a6f-bcf2bd224492.png)

I tried the same credential in my iOS wallet, and was successful:

![image](https://user-images.githubusercontent.com/14081049/72633021-95526680-3925-11ea-846c-7bb85e222374.png)

We can't see anything on our end that should be causing this. Could it be an Android bug?

**Comment by AnthonyRonning** [comment]
Could be, have them submit their logs to you and provide them here if you can or identify key log messages yourself and paste them.

**Comment by mlisle** [comment]
This appears to be the relevant portion of the logs. We've seen it happen on 2 android devices now, both for certs that imported fine on iOS devices (and validate in the web validator).

```
[d] [20200206 10:20:33]ApiModule: response: Response{protocol=h2, code=200, message=, url=https://certs.blockcerts.gatech.edu/2d934e4f-8709-4c65-93f9-869a8045a3a8.json}
[e] [20200206 10:20:33]LMFragment: Displaying error
com.google.gson.JsonIOException: java.net.URISyntaxException: Illegal character in opaque part at index 21: ecdsa-koblitz-pubkey: 1KYBRCkx8ExNRKfaMkpHhs5XQkYnKaotzb
	at com.google.gson.internal.bind.TypeAdapters$22.read(TypeAdapters.java:512)
	at com.google.gson.internal.bind.TypeAdapters$22.read(TypeAdapters.java:501)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:953)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at com.learningmachine.android.app.data.cert.BlockCertAdapter.deserialize(BlockCertAdapter.java:32)
	at com.learningmachine.android.app.data.cert.BlockCertAdapter.deserialize(BlockCertAdapter.java:16)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at com.google.gson.Gson.fromJson(Gson.java:774)
	at com.learningmachine.android.app.data.cert.BlockCertParser.fromJson(BlockCertParser.java:24)
	at com.learningmachine.android.app.data.CertificateManager.handleCertificateResponse(CertificateManager.java:100)
	at com.learningmachine.android.app.data.CertificateManager.lambda$addCertificate$0$CertificateManager(CertificateManager.java:74)
	at com.learningmachine.android.app.data.-$$Lambda$CertificateManager$qqtF0F1tPdqTmlMqc2I6NCPj3qk.call(Unknown Source:4)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onNext(OperatorSubscribeOn.java:74)
	at retrofit2.adapter.rxjava.BodyOnSubscribe$BodySubscriber.onNext(BodyOnSubscribe.java:51)
	at retrofit2.adapter.rxjava.BodyOnSubscribe$BodySubscriber.onNext(BodyOnSubscribe.java:39)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:36)
	at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:28)
	at rx.Observable.unsafeSubscribe(Observable.java:10256)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 21: ecdsa-koblitz-pubkey: 1KYBRCkx8ExNRKfaMkpHhs5XQkYnKaotzb
	at java.net.URI$Parser.fail(URI.java:2892)
	at java.net.URI$Parser.checkChars(URI.java:3065)
	at java.net.URI$Parser.parse(URI.java:3102)
	at java.net.URI.<init>(URI.java:583)
	at com.google.gson.internal.bind.TypeAdapters$22.read(TypeAdapters.java:510)
	... 39 more
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: okhttp3.ResponseBody$1.class
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
	... 19 more
```

**Comment by AnthonyRonning** [comment]
`Illegal character in opaque part at index 21: ecdsa-koblitz-pubkey: 1KYBRCkx8ExNRKfaMkpHhs5XQkYnKaotzb`

Looks like there's a space that shouldn't be there?

**Comment by stuartf** [comment]
I figured that was what the error is saying, but why does only Android treat that as a URI?

**Comment by AnthonyRonning** [comment]
I'm not sure. It sounds like a bug that the iOS app *doesn't* treat it as an invalid certificate, given that the schema defines that field as a URI https://github.com/blockchain-certificates/cert-schema/blob/master/cert_schema/2.0/recipientSchema.json#L15

**Comment by mlisle** [comment]
Closing this issue -- the space was the problem.
